version: '2'

services:
  todo_srvr:
    image: 'abdulsaidov/todo_srvr'
    build:
      context: src/main/docker
    container_name: todo_srvr
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    ports:
        - "5432:5432"
  front:
    image: 'abdulsaidov/todo_front'
    container_name: front
    ports:
      - "1337:1337"